
// SCREEN TYPE

package game.ui;

public enum ScreenType
{
    DEBUG_GENERATE,
    EXIT,
    STAY,
    MAIN,
    OPTIONS,
    HUB,
    CHARACTER,
    EQUIPMENT,
    EQUIPPED_ITEM,
    INVENTORY,
    INVENTORY_ITEM_LIST,
    INVENTORY_ITEM,
    STASH,
    DEPOSIT,
    DEPOSIT_WEAPON_LIST,
    DEPOSIT_ARMOR_LIST,
    DEPOSIT_JUNK_LIST,
    DEPOSIT_WEAPON,
    DEPOSIT_ARMOR,
    DEPOSIT_JUNK,
    WITHDRAW,
    WITHDRAW_WEAPON_LIST,
    WITHDRAW_ARMOR_LIST,
    WITHDRAW_JUNK_LIST,
    WITHDRAW_WEAPON,
    WITHDRAW_ARMOR,
    WITHDRAW_JUNK,
    SHOP,
    BUY,
    SELL
}